- name: Install WireGuard
  apt:
    name: wireguard
    state: present
  become: yes

- name: Configure WireGuard
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'
  become: yes
- name: Ensure WireGuard package is installed
  apt:
    name: wireguard
    state: present

- name: Configure WireGuard interface
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600

- name: Enable and start WireGuard service
  systemd:
    name: wg-quick@wg0
    state: started
    enabled: yes
