- name: Install Python and Flask
  apt:
    name:
      - python3
      - python3-pip
    state: present
  become: yes

- name: Install Flask and other required packages
  pip:
    name:
      - flask
      - flask-sqlalchemy
      - flask-login
    state: present
    executable: pip3
